language: php

php:
  - 5.3
  
addons:
  code_climate:
    repo_token: 75c44bafd5d510d5a8dec4855ff28d120a2f15ee05c0e16d4969c68948542352

install:
  - composer install

before_script:
  - composer self-update

script: phpunit --coverage-text

notifications:
  email:
    - gb@tekkie.ro

after_script:
  - vendor/bin/test-reporter
